(function(){
  function parseCsv(text){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(value);value=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(Boolean))rows.push(row);row=[];value=''}else value+=ch}if(value||row.length){row.push(value);rows.push(row)}const keys=rows.shift()||[];return rows.map(r=>Object.fromEntries(keys.map((k,i)=>[k,r[i]||''])))}
  function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function panel(title){return [...document.querySelectorAll('.dash-main h3,.dash-main h4,.dash-main .dash-panel__title')].find(x=>x.textContent.trim()===title)?.closest('.rank-panel,.event-list,.summary,.dash-panel')}
  function mount(){const main=document.querySelector('.dash-main');if(!main||main.dataset.web7)return false;const parts={events:panel('实时协同事件'),map:panel('京津冀协同发展指数地图'),active:panel('协同活跃度（近7日）'),resources:panel('教育资源分布概览'),pie:panel('高校合作项目类型'),radar:panel('五维协同分析'),cloud:panel('政策热点词云'),rank:panel('协同指数排名（区域）'),forecast:panel('趋势预测（未来5年）')};if(!parts.map||!parts.events)return false;
    const left=document.createElement('div'),center=document.createElement('div'),right=document.createElement('div');left.className='web7-col web7-col--left';center.className='web7-col web7-col--center';right.className='web7-col web7-col--right';
    const dimension=document.createElement('section');dimension.className='web7-dimension';dimension.innerHTML='<div class="web7-dimension__title">分维度协同观测</div><table class="web7-dimension__table"><thead><tr><th>维度</th><th>北京</th><th>天津</th><th>河北</th></tr></thead><tbody><tr><td>教育协同</td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td></tr><tr><td>科技协同</td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td></tr><tr><td>人才协同</td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td></tr><tr><td>产教融合</td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td><td><span class="web7-dimension__placeholder">—</span></td></tr></tbody></table><div class="web7-dimension__note">分维度评分字段待补充；当前为页面占位展示，不参与数据库统计。</div>';
    parts.map.appendChild(dimension);
    const network=document.createElement('section');network.className='web7-network-panel';network.innerHTML='<div class="web7-network-head">合作网络图 <small style="color:#6d89a8;font-weight:400">（主体关联强度）</small></div><button class="web7-network-link" type="button">进入完整网络 ›</button><iframe class="web7-network-frame" title="合作网络图" src="./network/index.html"></iframe>';
    network.querySelector('button').onclick=()=>{[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='协同监测')?.click()};const networkFrame=network.querySelector('iframe');networkFrame.onload=()=>{try{const d=networkFrame.contentDocument,s=d.createElement('style');s.textContent='.brand,.filters,.side{display:none!important}html,body{margin:0!important;overflow:hidden!important;background:#07152e!important}.network{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;min-height:0!important;border:0!important;border-radius:0!important;background:#07152e!important}#canvas{width:100%!important;height:100%!important;filter:invert(1) hue-rotate(180deg) brightness(.78) saturate(1.55)}.metrics{top:10px!important;left:10px!important}.legend{bottom:8px!important}';d.head.appendChild(s);networkFrame.contentWindow.dispatchEvent(new Event('resize'))}catch(e){}};
    [parts.events,parts.cloud,parts.rank].filter(Boolean).forEach(x=>left.appendChild(x));[parts.map,parts.active,parts.resources].filter(Boolean).forEach(x=>center.appendChild(x));[parts.forecast,network,parts.radar||parts.pie].filter(Boolean).forEach(x=>right.appendChild(x));main.replaceChildren(left,center,right);main.className='dash-main web7-home-grid';main.dataset.web7='1';
    const eTitle=parts.events.querySelector('h3');if(eTitle)eTitle.textContent='协同事件热度榜';const mapTitle=parts.map.querySelector('h3,.dash-panel__title');if(mapTitle)mapTitle.textContent='京津冀教育协同活跃度地图';const activeTitle=parts.active?.querySelector('h3,.dash-panel__title');if(activeTitle)activeTitle.textContent='月度协同事件动态演变';document.body.insertAdjacentHTML('beforeend','<div class="web7-data-badge">数据来源：节点表.csv · 关系表.csv · 事件审核明细.csv</div>');applyData(parts);setInterval(()=>applyData(parts),2000);return true}
  function applyData(parts){if(!window.WEB7_DASH)return;const {values,hot,regions}=window.WEB7_DASH;const titles=['教育协同指数','跨省市协同占比','最新日期协同事件','最新月份协同事件','累计合作关系','参与主体总数'];document.querySelectorAll('.stat-card').forEach((card,i)=>{if(i>=6)return;const t=card.querySelector('.stat-card__title'),n=card.querySelector('.stat-card__number'),u=card.querySelector('.stat-card__unit');if(t&&t.textContent!==titles[i])t.textContent=titles[i];if(n&&n.textContent!==String(values[i]))n.textContent=values[i];if(u)u.textContent=i===0?'分':i===1?'%':''});
    const scroll=parts.events.querySelector('.event-list__scroll');if(scroll&&!scroll.dataset.web7){scroll.dataset.web7='1';scroll.innerHTML=[...hot,...hot].map((e,i)=>`<div class="event-item"><div class="event-item__tag event-item__tag--${i%3===0?'education':i%3===1?'technology':'talent'}">${esc(e.tag)}</div><div class="event-item__content"><p class="event-item__title">${esc(e.title)}</p><div class="event-item__meta"><span>${esc(e.date)}</span></div></div></div>`).join('')}
    parts.rank?.querySelectorAll('.rank-item').forEach((item,i)=>{const r=regions[i];if(!r)return;item.querySelector('.rank-item__name').textContent=r.name==='河北'?'河北省':r.name+'市';item.querySelector('.rank-item__region').textContent=r.name;item.querySelector('.rank-item__score').textContent=r.score.toFixed(1);item.querySelector('.rank-item__bar').style.width=r.score+'%'});
  }
  let tries=0,timer=setInterval(()=>{if(mount()||++tries>80)clearInterval(timer)},100);
})();
